### ISSUE TITLE
[Bug] Error in the console

### ISSUE THREAD

**Issue by Lennord** [JustixDevelopment/PermissionSystem#3]
Hello, every time I connect to the server, I get an error.

Version: Paper-1.16.5
Version of Plugin: 4.8
Error: https://pastebin.com/w6x6mkVg

I hope you can fix this problem, thanks.

**Comment by JustixDevelopment** [comment]
The problem occurs because you are using a < 3 months old paper jar (probably because of Log4J) and the plugin only supports the old ones.

**Comment by Lennord** [comment]
Okay, I tried with recent version of Paper 1.18.2 and it works fine and no errors, thank you very much.
